- name: Check if sdkman is already installed
  stat:
    path: /tmp/sdkman.sh
  register: install_script

- name: Download and run installation if not already installed
  block:

  - name: Install required tools
    become: true
    package:
      name:
        - unzip
        - zip

  - name: Download sdkman installation script
    get_url:
      url: https://get.sdkman.io
      dest: /tmp/sdkman.sh
      mode: '0755'

  - name: Run installation script
    become: true
    shell:
      cmd: /tmp/sdkman.sh

  - name: Set sdkman_installed fact
    set_fact:
      sdkman_installed: true

  when: not install_script.stat.exists
