- import_role:
    name: comcast.sdkman
  vars:
    sdkman_user: "{{ ansible_user_id }}"
    sdkman_group: "{{ ansible_user_id }}"
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - { candidate: java }
      - { candidate: gradle }
      - { candidate: maven }
      - { candidate: kotlin }
      - { candidate: quarkus }

