- name: Download Azure CLI installation script
  get_url:
    url: https://aka.ms/InstallAzureCLIDeb
    dest: /tmp/InstallAzureCLIDeb.sh
    mode: '0755'

- name: Run installation script
  become: true
  shell:
    cmd: /tmp/InstallAzureCLIDeb.sh
