#!/usr/bin/bash

## Install Ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt- update -y
sudo apt install -y curl git software-properties-common ansible

## Pull Ansible
sudo ansible-pull -U https://github.com/erikroed/ansible.git
