- hosts: localhost
  vars:
    home_path: "{{ ansible_facts['env']['HOME'] }}"
  roles:
    - { role: terminal, tags: terminal }
    - { role: gui, tags: gui }
    - { role: os, tags: os }
  ignore_errors: yes
