- hosts: localhost
  gather_facts: true

  pre_tasks:
    - name: Ensure jq is installed
      become: true
      package:
        name: jq
        state: present
      tags: zen

  roles:
    - role: cli
      tags: cli
    - role: docker
      tags: docker
    - role: k8s-tools
      tags: k8s-tools
    - role: zen
      tags: zen

  ignore_errors: yes
