- hosts: localhost
  gather_facts: true

  roles:
    - role: cli
      tags: cli
    - role: docker
      tags: docker
    - role: k8s-tools
      tags: k8s-tools
    - role: node
      tags: node
    - role: zen
      tags: zen

  ignore_errors: yes
