- hosts: localhost
  gather_facts: true

  pre_tasks:
    - name: Ensure jq is installed
      become: true
      package:
        name: jq
        state: present
      tags: zen

  roles:
    - role: cli
      tags: cli
    - role: docker
      tags: docker
    - role: k8s-tools
      tags: k8s-tools
    - role: neovim
      tags: neovim
    - role: ssh
      tags: ssh

  tasks:
    - name: Source ~/.bashrc
      debug:
        msg: "Remember to run 'source ~/.bashrc'"

  ignore_errors: yes
