- hosts: localhost
  gather_facts: true

  roles:
    - role: cli
      tags: cli
    - role: docker
      tags: docker
    - role: kubernetes
      tags: kubernetes
    - role: node
      tags: node
    - role: zen
      tags: zen

  ignore_errors: yes
