- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
        - discord
        - telegram
        - brave
        - spotify
  tasks:
    - include_tasks: tasks/zsh.yaml
    - include_tasks: tasks/node.yaml
    - include_tasks: tasks/dotfiles.yaml
    - include_tasks: tasks/git-setup.yaml
    - include_tasks: tasks/brave.yaml
    - include_tasks: tasks/discord.yaml
    - include_tasks: tasks/telegram.yaml
    - include_tasks: tasks/spotify.yaml
      tags: always
