- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
  tasks:
    - include: tasks/zsh.yaml
    - include: tasks/node.yaml
