- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "post@erikroed.no"
  tags:
  - git
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "erikroed"
  tags:
  - git