- name: Install stow
  package:
    name: stow

- name: Cloning dotfiles
  git:
    repo: https://github.com/erikroed/dotfiles.git
    dest: "{{ lookup('env', 'USER') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Stow dotfiles
  shell: cd "{{ lookup('env', 'HOME') }}"/.dotfiles && ./ubuntu
