- name: Install stow
  become: true
  package:
    name: stow

- name: Cloning dotfiles
  become: true
  git:
    repo: https://github.com/erikroed/dotfiles.git
    dest: "{{ dotfiles_path }}"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Set correct owner and group to repo
  become: true
  file:
    path: "{{ dotfiles_path }}"
    recurse: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Stow dotfiles
  become: true
  shell: cd "{{ dotfiles_path }}" && ./ubuntu
  environment:
    HOME: "/home/{{ ansible_user_id }}"
