- name: Add Spotify signing key
  become: true
  ansible.builtin.apt_key:
    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    state: present
  tags: 
    - install
    - spotify

- name: Add Spotify repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
  tags: 
    - install
    - spotify

- name: Update cache and install Spotify Client
  become: true
  apt:
    update_cache: true
    name: spotify-client
  tags: 
    - install
    - spotify
    
