- name: Ensure apt is the package manager
  command:
    cmd: which apt
  register: apt_check
  failed_when: apt_check.rc != 0

- name: Fail if apt is not the package manager
  assert:
    that:
      - apt_check.rc == 0
    fail_msg: "Spotify for Linux is only supported for debian distros with apt package manager"

- name: Add Spotify signing key
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    state: present

- name: Add Spotify repository into sources list
  become: true
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Update cache and install Spotify Client
  become: true
  apt:
    update_cache: true
    name: spotify-client
