- name: Install required packages
  become: true
  package:
    name:
      - liboss4-salsa-asound2
    state: present

- name: Install discord
  become: true
  package:
    deb: https://discord.com/api/download?platform=linux&format=deb
    update_cache: true
