- name: Download and install Microsoft GPG key
  shell: "curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null"

- name: Set permissions for Microsoft GPG key
  file:
    path: /etc/apt/keyrings/microsoft.gpg
    mode: '0644'

- name: Add Azure CLI repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main" 
    state: present
    filename: azure-cli

- name: Update cache and install az
  apt:
    update_cache: yes
    name: azure-cli
    state: present
