- name: Install fzf
  apt:
    name: fzf
    update_cache: true
  tags:
    - fzf

- name: install node
  apt:
    name: ['nodejs', 'npm']
  tags:
    - node

- name: Install tmux
  apt:
    name: tmux
  tags:
    - tmux
