- import_role:
    name: gantsign.ansible-role-golang
  vars:
    golang_version: '1.21.4'
    golang_install_dir: '/opt/go/{{ golang_version }}'
    golang_redis_sha256sum: '73cac0215254d0c7d1241fa40837851f3b9a8a742d0b54714cbdfb3feaf8f0af'
    golang_gopath: '/usr/local/go/bin/'
