- name: Install cli tools
  become: true
  import_tasks: cli.yml
  tags: cli

- name: Install neovim
  become: true
  import_tasks: nvim.yml
  tags: neovim

- name: Clone and stow dotfiles
  import_tasks: dotfiles.yml
  tags: dotfiles

- name: Install GitHub CLI
  become: true
  import_tasks: github.yml
  tags: gh

- name: Configure git
  import_tasks: git.yml
  tags: git

- name: Install docker
  become: true
  import_tasks: docker.yml
  tags: docker

- name: Install and configure sdkman
  import_tasks: sdkman.yml
  tags: sdkman

- name: Task for ssh
  become: true
  import_tasks: ssh.yml
  tags: ssh

- name: Install rust
  import_tasks: rust.yml
  tags: rust

- name: Install python stuff
  become: true
  import_tasks: python3.yml
  tags: python

- name: Install Go
  become: true
  import_tasks: golang.yml
  tags:
    - go
    - golang

- name: Install terraform
  become: true
  import_tasks: terraform.yml
  tags:
    - terraform
    - tf

- name: Install azure-cli
  become: true
  import_tasks: azure-cli.yml
  tags:
    - az
    - azure

- name: Remember to reload shell with the following command
  debug:
    msg: "source ~/.bashrc"
