- name: Update apt cache before installing Rust
  become: true
  apt:
    update_cache: true

- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download rust installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '07555'
    force: 'yes'

- name: Run rust installer
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
