- import_role:
    name: comcast.sdkman
  vars:
    sdkman_user: "{{ ansible_user_id }}"
    sdkman_group: "{{ ansible_user_id }}"
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_install_packages:
      - { candidate: java, version: 20.0.2-graalce }
      - { candidate: gradle, version: 8.3 }
      - { candidate: maven, version: 3.9.4 }
      - { candidate: kotlin, version: 1.9.0 }
      - { candidate: quarkus, version: 3.3.2 }
    sdkman_defaults:
      java: 20.0.2-graalce
      gradle: '8.3'
      maven: 3.9.4
      kotlin: 1.9.0
      quarkus: 3.3.2
