- name: Install dependencies
  become: true
  package:
    update_cache: true
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }}/ {{ ansible_lsb.codename }} stable"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Install Docker
  package:
    name: docker-ce
    state: present

- name: Create docker group if not exists
  group:
    name: docker
    state: present

- name: Add {{ ansible_user }} to group docker
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: true
