- name: Ensure wget is available
  become: true
  package:
    name: wget
    state: present

- name: Install gh cli for distros using apt as package manager
  become: true
  block:

  - name: Create directory for keyrings
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download GPG key
    get_url:
      url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
      dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
      mode: '0644'

  - name: Add repo to APT sources
    apt_repository:
      repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
      filename: github-cli

  - name: Update cache and install
    package:
      update_cache: true
      name: gh
      state: present

  when: ansible_pkg_mgr == 'apt'
