- name: Install CLI-tools
  become: true
  package:
    update_cache: true
    state: present
    name:
      - jq
      - fzf
      - tmux
      - fd-find

- name: Install ripgrep
  block:
    - name: Get latest ripgrep version
      uri:
        url: https://api.github.com/repos/BurntSushi/ripgrep/releases/latest
        return_content: yes
      register: ripgrep_releases

    - name: Set ripgrep release version
      set_fact:
        ripgrep_deb_url: "{{ (ripgrep_releases.json.assets | json_query('[?ends_with(browser_download_url, `.deb`)]'))[0].browser_download_url }}"

    - name: Install binary
      become: true
      package:
        deb: "{{ ripgrep_deb_url }}"
        state: present
  tags: ripgrep
